### ISSUE TITLE
coco-caption is needed

### ISSUE THREAD

**Issue by jamiechoi1995** [aditya12agd5/convcap#2]
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from train import train 
  File "/home/wcai/convcap/convcap/train.py", line 25, in <module>
    from test import test 
  File "/home/wcai/convcap/convcap/test.py", line 23, in <module>
    from evaluate import language_eval
  File "/home/wcai/convcap/convcap/evaluate.py", line 14, in <module>
    from pycocotools.coco import COCO
ImportError: No module named pycocotools.coco

Since evaluate.py is modified from https://github.com/karpathy/neuraltalk2/blob/master/coco-caption/myeval.py,
https://github.com/tylin/coco-caption is needed for convcap.

However, in README.md, this is not mentioned.
I think some instruction like "download https://github.com/tylin/coco-caption and extract it in the same folder" is needed.

Thanks.

**Comment by aditya12agd5** [comment]
coco-caption is added a git submodule. I will update the Readme to say that the repository is to be cloned as 'git clone --recursive <url>'. Thanks for pointing it out.
