### ISSUE TITLE
Required Hardware

### ISSUE THREAD

**Issue by ObadaAljabasini** [aditya12agd5/convcap#4]
Hello,
I plan to use this repo to train a model, can you please provide your setup(gpu, cpu, time for epoch etc..)?

**Comment by aditya12agd5** [comment]
On Nvidia Titan Xp ( https://www.nvidia.com/en-us/titan/titan-xp/ ) and Intel Xeon CPU E5-2620 (2.40GHz), it takes roughly ~30mins per training epoch.
