### ISSUE TITLE
How to generate wordlist.p for new dataset?

### ISSUE THREAD

**Issue by mitalbert** [aditya12agd5/convcap#5]
Hi, I want to combine flickr and coco together for better generalization, but I'm not sure how wordlist.p is generated and I could not find any script on the repository that does it. Would you please help with that?

**Comment by jyotianeja** [comment]
For the wordlist, we considered all the words that occur more than 5 times
in the training data.

**Comment by mitalbert** [comment]
Thanks @jyotianeja , besides the words there also other rows with p* and I*:

Vraining
p1
I0
sVwritings
p2
I4540

but after having looked at the code, I am assuming these rows are not relevant?

**Comment by mitalbert** [comment]
@jyotianeja and one more question. Is there a specific reason why you chose vgg16 instead of say resnet or any other more complex CNN?

**Comment by jyotianeja** [comment]
It is a pickle file. You should load it using something like:
import pickle
data = pickle.load(open('wordlist.p','r'))
data should be a dictionary of size 9221
len(data) should give you 9221
and type(data ) should be dict

To answer your second question, we use VGG16 to make a fair comparison to
neural talk 2. Although in the final version of the paper in table 5, we do
show that using ResNet improves performance of both the methods.
http://openaccess.thecvf.com/content_cvpr_2018/papers/Aneja_Convolutional_Image_Captioning_CVPR_2018_paper.pdf

**Comment by mitalbert** [comment]
@jyotianeja thanks, I will then add flickr words to the wordlist.

I see, so resnet makes big difference. Are you going to upload the resnet version or do I have to implement it myself?

**Comment by aditya12agd5** [comment]
You can see the devel branch and in particular this commit ( https://github.com/aditya12agd5/convcap/commit/01844ec185479fa532f9c9399c949b9524775a33 ) for code with resnet support. I will merge it to master when I look at this code again (~Fall).

**Comment by zzy-ucas** [comment]
@mitalbert Did you get the code for generating the file "wordlist.p" for new dataset? I can only guess the "wordlist.p" that contains a vocabulary with type 'dict()'. However I do not know how to create this "wordlist.p". @jyotianeja Could you help me with that? Thanks a lot! Orz....

**Comment by mitalbert** [comment]
@zzy-ucas I did not, I will share it with you as soon as I write a script for that.

**Comment by zzy-ucas** [comment]
@mitalbert It's very nice of you. I found that the type of the vocabulary in this "wordlist.p" is dict(), the keys with type of unicode, the values with type of int. Maybe this can help U a lot. :)

**Comment by cike14** [comment]
@mitalbert  can you share the script (generate the file "wordlist.p" ) for me?
